Bookchat/models.py
from Bookchat import db

class rank(db.Model):
    index = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)

class buy(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    brand = db.Column(db.String(200), nullable=False)
    lprice = db.Column(db.String(200), nullable=False)
    image = db.Column(db.String(200), nullable=True)
    address = db.Column(db.String(200), nullable=False)
    buy_date = db.Column(db.DateTime(), nullable=False)

Bookchat/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField , PasswordField
from wtforms.fields.html5 import EmailField
from wtforms.validators import  DataRequired,Length,EqualTo,Email

class BookinfoForm(FlaskForm):
    title=StringField('책제목',validators=[DataRequired()])

class MovieinfoForm(FlaskForm):
    title=StringField('영화제목',validators=[DataRequired()])

class ShopinfoForm(FlaskForm):
    name=StringField('상품이름',validators=[DataRequired()])

class ShopbuyForm(FlaskForm):
    address=StringField('주소',validators=[DataRequired()])

Bookchat/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
import config

app=Flask(__name__)
app.debug = True
app.config.from_object(config)

db = SQLAlchemy()
migrate = Migrate()
# ORM
db.init_app(app)
migrate.init_app(app, db)

from .views import main_views,movie_views,shop_views
app.register_blueprint(main_views.bp)
app.register_blueprint(movie_views.bp)
app.register_blueprint(shop_views.bp)

#필터등록
from .filter import Shortword,Replacebar
app.jinja_env.filters['shortword'] = Shortword
app.jinja_env.filters['barhide'] = Replacebar

Bookchat/views/main_views.py
from flask import Blueprint , render_template , request, url_for, g,flash,request
from werkzeug.utils import redirect
from Bookchat.forms import BookinfoForm
from Bookchat.Naverbookapi import Naverbook
import json

bp = Blueprint('main',__name__,url_prefix='/')

@bp.route('/')
def Main():
    return render_template('base.html')

@bp.route('/bookinfo' , methods=('POST','GET'))
def Bookinfo():
    form = BookinfoForm()

    if request.method == 'POST' and form.validate_on_submit():
        print(form.title.data)
        result =  Naverbook(form.title.data)
        result = json.loads(result)
        return render_template('book_info.html',book_info_list = result['items'], form=form)
        #네이버에서 위의 타이틀에 해당하는 책의 정보를 가져와서 html로 넘겨서 화면에 나오게한다.



    return render_template('book_info.html',form=form)

Bookchat/views/movie_views.py
from flask import Blueprint , render_template , request, url_for, g,flash,request
from werkzeug.utils import redirect
from Bookchat.forms import MovieinfoForm
from Bookchat.Navermovieapi import Navermovie,Movierank
import json
from ..models import rank

bp = Blueprint('movie',__name__,url_prefix='/movie')


@bp.route('/info' , methods=('POST','GET'))
def Movieinfo():
    form = MovieinfoForm()

    if request.method == 'POST' and form.validate_on_submit():
        print(form.title.data)
        result =  Navermovie(form.title.data)
        result = json.loads(result)
        return render_template('movie_info.html',movie_info_lst = result['items'], form=form)
        #네이버에서 위의 타이틀에 해당하는 책의 정보를 가져와서 html로 넘겨서 화면에 나오게한다.


    return render_template('movie_info.html',form=form)


@bp.route('/rank')
def Getmovierank():

    data = rank.query.all()
    print('-----------',data)

    data_list = []
    for temp in data:
        data_list.append(temp.title)

    movierank = Movierank()


    return render_template('movie_rank.html',movie_rank_lst=data_list)

Bookchat/views/shop_views.py
from flask import Blueprint , render_template , request, url_for, g,flash,request
from werkzeug.utils import redirect
from Bookchat.forms import ShopinfoForm,ShopbuyForm
from Bookchat.Navershopapi import Navershop
import json
from ..models import rank,buy
from Bookchat import db
from datetime import datetime

bp = Blueprint('shop',__name__,url_prefix='/shop')


@bp.route('/info' , methods=('POST','GET'))
def shopinfo():
    form = ShopinfoForm()

    if request.method == 'POST' and form.validate_on_submit():
        result = Navershop(form.name.data)
        result = json.loads(result)
        return render_template('shop_info.html', shop_info_lst=result['items'], form=form)
        # 네이버에서 위의 타이틀에 해당하는 책의 정보를 가져와서 html로 넘겨서 화면에 나오게한다.

    return render_template('shop_info.html', form=form)

@bp.route('/buy' , methods=['POST'])
def shopbuy():
    form = ShopbuyForm()
    stitle = request.form['title']
    sbrand = request.form['brand']
    slprice = request.form['lprice']
    simage = request.form['image']

    return render_template('shop_buy.html',stitle=stitle,sbrand=sbrand,slprice=slprice,
                           simage=simage,form=form)

@bp.route('/buysave' , methods=['POST'])
def buysave():
    title = request.form['title']
    brand = request.form['brand']
    price = request.form['lprice']
    image = request.form['image']
    address = request.form['address']


    btemp =  buy(title=title, brand=brand, lprice=price, image=image,
                 address=address, buy_date=datetime.now())
    db.session.add(btemp)
    db.session.commit()
    return '상품구매를 완료하였습니다.'

Bookchat/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">

    <title>네이버정보 챗봇</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{{ url_for('main.Main') }}">네이버검색 챗봇</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{{url_for('main.Bookinfo')}}">책정보</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{url_for('movie.Movieinfo')}}">영화정보</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{url_for('movie.Getmovierank')}}">영화순위</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{url_for('shop.shopinfo')}}">최저가검색</a>
            </li>
        </ul>
    </div>
</nav>


{% block content %}

{% endblock %}

<script src ="{{ url_for('static',filename='jquery-3.5.1.min.js') }}" > </script>
<script src ="{{ url_for('static',filename='bootstrap.min.js') }}" > </script>
{% block script %}

{% endblock %}

</body>
</html>

Bookchat/templates/book_info.html
{% extends 'base.html' %}

{% block content %}
<div>
    <form action="{{url_for('main.Bookinfo')}}" method="post" class="post-form my-3 ml-3">

            {{ form.csrf_token }}

            {{ form.title.label }}
            {{ form.title(class='form-control') }}
            <button type="submit" class="btn btn-primary my-2">정보 가져오기</button>
    </form>
</div>
{% if book_info_list %}
<div class="container my-3">
    <table class="table table-hover " style="font-size: 12px" >
        <thead>
            <tr class="text-center thead-dark">
                <th style="width: 10%">번호</th>
                <th style="width: 40%">제목</th>
                <th style="width: 40%">내용</th>
                <th style="width: 10%">작가</th>

            </tr>
        </thead>
        <tbody>
        {% for temp in book_info_list %}
        <tr class="text-center">
             <td>{{ loop.index }}</td>
             <td>{{ temp.title | safe }}</td>
             <td>{{ temp.description | safe | shortword }}</td>
             <td>{{ temp.author | safe | shortword }}</td>

         </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}
{% endblock %}

Bookchat/templates/movie_info.html
{% extends 'base.html' %}

{% block content %}
<div>
    <form action="{{url_for('movie.Movieinfo')}}" method="post" class="post-form my-3 ml-3">

            {{ form.csrf_token }}

            {{ form.title.label }}
            {{ form.title(class='form-control') }}
            <button type="submit" class="btn btn-primary my-2">정보 가져오기</button>
    </form>
</div>
{% if movie_info_lst %}
<div class="container my-3">
    <table class="table table-hover " style="font-size: 12px" >
        <thead>
            <tr class="text-center thead-dark">
                <th style="width: 10%">번호</th>
                <th style="width: 40%">제목</th>
                <th style="width: 20%">년도</th>
                <th style="width: 30%">배우</th>
                <th style="width: 10%">평점</th>
                <th style="width: 10%">이미지</th>
            </tr>
        </thead>
        <tbody>
        {% for temp in movie_info_lst %}
        <tr class="text-center">
             <td>{{ loop.index }}</td>
             <td>{{ temp.title | safe | barhide}}</td>
             <td>{{ temp.pubDate | safe | barhide}}</td>
             <td>{{ temp.actor | safe | shortword| barhide }}</td>
             <td>{{ temp.userRating | safe | shortword | barhide}}</td>
             <td><img src={{ temp.image }} alt="My Image"></img></td>
         </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}
{% endblock %}

Bookchat/templates/movie_rank.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <table class="table table-hover " style="font-size: 12px" >
        <thead>
            <tr class="text-center thead-dark">
                <th style="width: 30%">순위</th>
                <th style="width: 70%">제목</th>
            </tr>
        </thead>
        <tbody>
        {% for temp in movie_rank_lst %}
        <tr class="text-center">
             <td>{{ loop.index }}</td>
             <td>{{ temp | safe }}</td>
         </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

Bookchat/templates/shop_buy.html
{% extends 'base.html' %}

{% block content %}
<div> 제품명 : {{ stitle }} </div>
<div> 브렌드 : {{ sbrand }} </div>
<div> 가격 : {{ slprice }} </div>
<div> <img src={{ simage }} height="100" width="100" alt="제품이미지"></img> </div>
<div> 주소 : {{ form.address }}</div>

<form action="{{url_for('shop.buysave')}}" method="post" class="post-form my-3 ml-3">
                 <input type="hidden" name="title" value={{stitle}}>
                 <input type="hidden" name="brand" value={{sbrand}}>
                 <input type="hidden" name="lprice" value={{lprice}}>
                 <input type="hidden" name="image" value={{slprice}}>
                 <input type="hidden" name="address" value={{form.address.data}}>
                 <button type="submit" class="btn btn-primary my-2">구매하기</button>
             </form>

{% endblock%}

Bookchat/templates/shop_info.html
{% extends 'base.html' %}

{% block content %}
<div>
    <form action="{{url_for('shop.shopinfo')}}" method="post" class="post-form my-3 ml-3">

            {{ form.csrf_token }}

            {{ form.name.label }}
            {{ form.name(class='form-control') }}
            <button type="submit" class="btn btn-primary my-2">정보 가져오기</button>
    </form>
</div>
{% if shop_info_lst %}
<div class="container my-3">
    <table class="table table-hover " style="font-size: 12px" >
        <thead>
            <tr class="text-center thead-dark">
                <th style="width: 10%">번호</th>
                <th style="width: 30%">제품명</th>
                <th style="width: 10%">브렌드</th>
                <th style="width: 10%">최저가</th>
                <th style="width: 10%">최고가</th>
                <th style="width: 10%">이미지</th>
            </tr>
        </thead>
        <tbody>
        {% for temp in shop_info_lst %}
        <tr class="text-center">
             <td>{{ loop.index }}</td>
             <td>{{ temp.title}}</td>
             <td>{{ temp.brand}}</td>
             <td>{{ temp.lprice}}</td>
             <td>{{ temp.hprice}}</td>
             <td><img src={{ temp.image }} height="100" width="100" alt="제품이미지"></img></td>
             <td> <form action="{{url_for('shop.shopbuy')}}" method="post" class="post-form my-3 ml-3">
                 <input type="text" name="title" maxlength="100" value={{temp.title}}>
                 <input type="text" name="brand" maxlength="100" value={{temp.brand}}>
                 <input type="text" name="lprice" maxlength="100" value={{temp.lprice}}>
                 <input type="text" name="image" maxlength="100" value={{temp.image}}>
                 <button type="submit" class="btn btn-primary my-2">구매하기</button>
             </form></td>
         </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}
{% endblock %}